// <auto-generated />
using System;
using DatabaseSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseSchema.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250621151229_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabaseSchema.Models.LopHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaLopHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("integer");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ThoiGianTao")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("DatabaseSchema.Models.LopHoc_NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LopHocId")
                        .HasColumnType("integer");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ThoiGianYeuCau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrangThai")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LopHocId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("LopHoc_NguoiDung");
                });

            modelBuilder.Entity("DatabaseSchema.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LoaiNguoiDung")
                        .HasColumnType("integer");

                    b.Property<string>("MatKhauBam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("DatabaseSchema.Models.LopHoc", b =>
                {
                    b.HasOne("DatabaseSchema.Models.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("DatabaseSchema.Models.LopHoc_NguoiDung", b =>
                {
                    b.HasOne("DatabaseSchema.Models.LopHoc", "LopHoc")
                        .WithMany("LopHoc_NguoiDung")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseSchema.Models.NguoiDung", "NguoiDung")
                        .WithMany("LopHoc_NguoiDung")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DatabaseSchema.Models.LopHoc", b =>
                {
                    b.Navigation("LopHoc_NguoiDung");
                });

            modelBuilder.Entity("DatabaseSchema.Models.NguoiDung", b =>
                {
                    b.Navigation("LopHoc_NguoiDung");
                });
#pragma warning restore 612, 618
        }
    }
}
